"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { LoaderCircle, Save, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { listClientsAction } from "@/app/dashboard/clientes/actions";
import type { ClientRecord } from "@/app/dashboard/clientes/clientes-data";
import { listCrmLeadsAction } from "@/features/crm/crm-actions";
import type { CrmLeadRecord } from "@/features/crm/crm-types";
import { Button } from "@/components/ui/button"; import { Field } from "@/components/ui/field"; import { Input } from "@/components/ui/input"; import { Select } from "@/components/ui/select";
import { ordemSchema, type OrdemFormInput, type OrdemFormValues } from "./ordens-schema"; import type { OrdemRecord } from "./ordens-types";
const defaults: OrdemFormInput = { clientId: "", crmLeadId: "", title: "", description: "", category: "CORRECTIVE", priority: "NORMAL", status: "OPEN", technician: "", address: "", city: "", state: "BA", scheduledDate: new Date().toISOString().slice(0, 10), scheduledTime: "08:00", estimatedDurationMinutes: 60, estimatedValue: 0, notes: "", checklistText: "Avaliar condições do local", equipmentText: "", materialsText: "" };
const fromOrder = (order?: OrdemRecord | null): OrdemFormInput => order ? { clientId: order.clientId, crmLeadId: order.crmLeadId ?? "", title: order.title, description: order.description, category: order.category, priority: order.priority, status: order.status, technician: order.technician, address: order.address, city: order.city, state: order.state, scheduledDate: order.scheduledDate, scheduledTime: order.scheduledTime, estimatedDurationMinutes: order.estimatedDurationMinutes, estimatedValue: order.estimatedValue, notes: order.notes, checklistText: order.checklist.map((item) => item.title).join("\n"), equipmentText: order.equipment.join("\n"), materialsText: order.reservedMaterials.join("\n") } : defaults;
export function OrdemFormDrawer({ open, order, saving, onClose, onSubmit }: { open: boolean; order?: OrdemRecord | null; saving: boolean; onClose: () => void; onSubmit: (values: OrdemFormValues) => Promise<void> }) {
  const [clients, setClients] = useState<ClientRecord[]>([]), [leads, setLeads] = useState<CrmLeadRecord[]>([]);
  const { register, handleSubmit, reset, formState: { errors } } = useForm<OrdemFormInput, unknown, OrdemFormValues>({ resolver: zodResolver(ordemSchema), defaultValues: defaults });
  useEffect(() => { if (open) { reset(fromOrder(order)); void Promise.all([listClientsAction(), listCrmLeadsAction()]).then(([clientItems, leadItems]) => { setClients(clientItems); setLeads(leadItems.filter((lead) => Boolean(lead.convertedClientId))); }); } }, [open, order, reset]);
  useEffect(() => { if (!open) return; const escape = (event: KeyboardEvent) => { if (event.key === "Escape" && !saving) onClose(); }; window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [onClose, open, saving]);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/55"><section role="dialog" aria-modal="true" aria-labelledby="ordem-form-title" className="proflow-scrollbar h-full w-full max-w-3xl overflow-y-auto bg-background shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between border-b bg-card/95 px-5 py-4"><div><h2 id="ordem-form-title" className="font-semibold">{order ? `Editar ${order.orderNumber}` : "Nova Ordem de Serviço"}</h2><p className="text-xs text-muted-foreground">Dados operacionais, agenda, vínculos e recursos.</p></div><Button variant="ghost" size="icon" onClick={onClose} disabled={saving} aria-label="Fechar"><X className="h-4 w-4" /></Button></header><form onSubmit={handleSubmit(onSubmit)} className="space-y-5 p-5">
    <fieldset className="grid gap-3 md:grid-cols-2"><legend className="col-span-full text-sm font-semibold">Vínculos</legend><Field label="Cliente" htmlFor="os-client" error={errors.clientId?.message} required><Select id="os-client" {...register("clientId")}><option value="">Selecione</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</Select></Field><Field label="Lead de origem" htmlFor="os-lead" error={errors.crmLeadId?.message}><Select id="os-lead" {...register("crmLeadId")}><option value="">Sem origem no CRM</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.name}</option>)}</Select></Field></fieldset>
    <fieldset className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><legend className="col-span-full text-sm font-semibold">Serviço</legend><Field label="Título" htmlFor="os-title" error={errors.title?.message} required className="md:col-span-2"><Input id="os-title" autoFocus {...register("title")} /></Field><Field label="Categoria" htmlFor="os-category" error={errors.category?.message}><Select id="os-category" {...register("category")}><option value="CLIMATIZATION">Climatização</option><option value="ELECTRICAL">Elétrica</option><option value="PREVENTIVE">Preventiva</option><option value="CORRECTIVE">Corretiva</option><option value="INSTALLATION">Instalação</option></Select></Field><Field label="Descrição" htmlFor="os-description" error={errors.description?.message} className="md:col-span-2 xl:col-span-3"><textarea id="os-description" className="min-h-20 w-full rounded-lg border bg-background p-2 text-sm" {...register("description")} /></Field><Field label="Prioridade" htmlFor="os-priority" error={errors.priority?.message}><Select id="os-priority" {...register("priority")}><option value="LOW">Baixa</option><option value="NORMAL">Normal</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></Select></Field><Field label="Status" htmlFor="os-status" error={errors.status?.message}><Select id="os-status" {...register("status")}><option value="OPEN">Aberta</option><option value="SCHEDULED">Agendada</option><option value="IN_TRANSIT">Em deslocamento</option><option value="IN_PROGRESS">Em execução</option><option value="WAITING_PART">Aguardando peça</option><option value="COMPLETED">Concluída</option><option value="OVERDUE">Atrasada</option></Select></Field><Field label="Técnico ou equipe" htmlFor="os-tech" error={errors.technician?.message}><Input id="os-tech" {...register("technician")} /></Field></fieldset>
    <fieldset className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><legend className="col-span-full text-sm font-semibold">Local e agenda</legend><Field label="Endereço" htmlFor="os-address" error={errors.address?.message} className="xl:col-span-2"><Input id="os-address" {...register("address")} /></Field><Field label="Cidade" htmlFor="os-city" error={errors.city?.message}><Input id="os-city" {...register("city")} /></Field><Field label="UF" htmlFor="os-state" error={errors.state?.message}><Input id="os-state" maxLength={2} {...register("state")} /></Field><Field label="Data prevista" htmlFor="os-date" error={errors.scheduledDate?.message}><Input id="os-date" type="date" {...register("scheduledDate")} /></Field><Field label="Horário" htmlFor="os-time" error={errors.scheduledTime?.message}><Input id="os-time" type="time" {...register("scheduledTime")} /></Field><Field label="Duração (minutos)" htmlFor="os-duration" error={errors.estimatedDurationMinutes?.message}><Input id="os-duration" type="number" min="15" step="15" {...register("estimatedDurationMinutes")} /></Field><Field label="Valor previsto" htmlFor="os-value" error={errors.estimatedValue?.message}><Input id="os-value" type="number" min="0" step="0.01" {...register("estimatedValue")} /></Field></fieldset>
    <fieldset className="grid gap-3 md:grid-cols-3"><legend className="col-span-full text-sm font-semibold">Execução</legend><Field label="Checklist inicial" htmlFor="os-checklist" error={errors.checklistText?.message}><textarea id="os-checklist" className="min-h-28 w-full rounded-lg border bg-background p-2 text-sm" placeholder="Um item por linha" {...register("checklistText")} /></Field><Field label="Equipamentos vinculados" htmlFor="os-equipment"><textarea id="os-equipment" className="min-h-28 w-full rounded-lg border bg-background p-2 text-sm" placeholder="Um equipamento por linha" {...register("equipmentText")} /></Field><Field label="Materiais reservados" htmlFor="os-materials"><textarea id="os-materials" className="min-h-28 w-full rounded-lg border bg-background p-2 text-sm" placeholder="Um material por linha" {...register("materialsText")} /></Field><Field label="Observações" htmlFor="os-notes" error={errors.notes?.message} className="md:col-span-3"><textarea id="os-notes" className="min-h-20 w-full rounded-lg border bg-background p-2 text-sm" {...register("notes")} /></Field></fieldset>
    <footer className="sticky bottom-0 flex justify-end gap-2 border-t bg-background/95 py-3"><Button type="button" variant="secondary" onClick={onClose} disabled={saving}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}{saving ? "Salvando..." : "Salvar OS"}</Button></footer>
  </form></section></div>;
}
