import type {
  AssetCondition,
  AssetOwnership,
  AssetStatus,
  AssetType,
  EquipmentStorageState,
} from "./equipamentos-types";
export const assetTypeLabels: Record<AssetType, string> = {
  TECHNICAL_EQUIPMENT: "Equipamento técnico",
  TOOL: "Ferramenta",
  VEHICLE: "Veículo",
  COMPUTER: "Informática",
  LIGHTING: "Iluminação",
  AUDIO: "Áudio",
  MEASUREMENT_INSTRUMENT: "Instrumento de medição",
  MACHINE: "Máquina",
  OTHER: "Outro",
};
export const ownershipLabels: Record<AssetOwnership, string> = {
  COMPANY: "Empresa",
  CUSTOMER: "Cliente",
  THIRD_PARTY: "Terceiro",
};
export const statusLabels: Record<AssetStatus, string> = {
  AVAILABLE: "Disponível",
  IN_USE: "Em uso",
  UNDER_MAINTENANCE: "Em manutenção",
  INACTIVE: "Inativo",
  RETIRED: "Retirado",
  LOST: "Perdido",
};
export const conditionLabels: Record<AssetCondition, string> = {
  GOOD: "Bom",
  ATTENTION: "Atenção",
  DAMAGED: "Danificado",
  UNUSABLE: "Inutilizável",
};
const now = "2026-07-15T12:00:00.000Z";
export const initialEquipmentState: EquipmentStorageState = {
  version: 3,
  revision: 0,
  nextSequence: 4,
  maintenanceRecords: [],
  serviceOrderLinks: [],
  assets: [
    {
      id: "asset-1",
      sequence: 1,
      internalCode: "EQ-0001",
      name: "Equipamento técnico demonstrativo",
      description: "Ativo durável para operação técnica.",
      assetType: "TECHNICAL_EQUIPMENT",
      category: "Operação técnica",
      manufacturer: "Fabricante demonstrativo",
      model: "Modelo técnico",
      serialNumber: "SER-0001",
      patrimonyNumber: "PAT-0001",
      ownership: "COMPANY",
      responsible: "Equipe técnica",
      location: { name: "Base operacional", room: "Área técnica" },
      acquisition: {
        acquisitionDate: "2025-01-15",
        acquisitionValueCents: 480000,
        supplier: "Fornecedor demonstrativo",
        invoiceNumber: "",
        purchaseReference: "",
        notes: "",
      },
      depreciation: {
        mode: "LINEAR",
        startDate: "2025-01-15",
        usefulLifeMonths: 60,
        residualValueCents: 30000,
      },
      status: "IN_USE",
      condition: "GOOD",
      photos: [],
      documents: [],
      notes: "",
      createdAt: now,
      updatedAt: now,
      history: [
        {
          id: "hist-1",
          type: "CREATED",
          message: "Ativo importado na carga inicial.",
          origin: "IMPORT",
          createdAt: now,
        },
      ],
    },
    {
      id: "asset-2",
      sequence: 2,
      internalCode: "EQ-0002",
      name: "Instrumento de medição demonstrativo",
      description: "Instrumento durável de medição.",
      assetType: "MEASUREMENT_INSTRUMENT",
      category: "Medição",
      manufacturer: "Fabricante demonstrativo",
      model: "Modelo digital",
      serialNumber: "SER-0002",
      patrimonyNumber: "PAT-0002",
      ownership: "COMPANY",
      responsible: "Equipe operacional",
      location: { name: "Base operacional", container: "Case técnico" },
      acquisition: {
        acquisitionDate: "2026-01-10",
        acquisitionValueCents: 125000,
        supplier: "",
        invoiceNumber: "",
        purchaseReference: "",
        notes: "",
      },
      depreciation: {
        mode: "LINEAR",
        startDate: "2026-01-10",
        usefulLifeMonths: 48,
        residualValueCents: 5000,
      },
      status: "AVAILABLE",
      condition: "ATTENTION",
      photos: [],
      documents: [],
      notes: "",
      createdAt: now,
      updatedAt: now,
      history: [
        {
          id: "hist-2",
          type: "CREATED",
          message: "Ativo importado na carga inicial.",
          origin: "IMPORT",
          createdAt: now,
        },
      ],
    },
    {
      id: "asset-3",
      sequence: 3,
      internalCode: "EQ-0003",
      name: "Ferramenta não depreciável",
      description: "Ferramenta de apoio operacional.",
      assetType: "TOOL",
      category: "Ferramentas",
      manufacturer: "",
      model: "",
      ownership: "THIRD_PARTY",
      responsible: "Equipe operacional",
      location: { name: "Área de apoio" },
      acquisition: {
        acquisitionValueCents: 0,
        supplier: "",
        invoiceNumber: "",
        purchaseReference: "",
        notes: "",
      },
      depreciation: { mode: "NONE", residualValueCents: 0 },
      status: "AVAILABLE",
      condition: "GOOD",
      photos: [],
      documents: [],
      notes: "",
      createdAt: now,
      updatedAt: now,
      history: [
        {
          id: "hist-3",
          type: "CREATED",
          message: "Ativo importado na carga inicial.",
          origin: "IMPORT",
          createdAt: now,
        },
      ],
    },
  ],
};
export type { EquipmentView } from "./equipamentos-types";
