export type ProFlowArea = "CLIMATIZATION" | "ELECTRICAL" | "IT";

export type ProFlowServiceCatalogItem = {
  id: string;
  name: string;
  area: ProFlowArea;
  description: string;
  unit: "SERVICE" | "HOUR" | "UNIT";
  priceCents: number;
  warrantyDays: number;
  checklist: string[];
  active: boolean;
};

export const proFlowAreaLabels: Record<ProFlowArea, string> = {
  CLIMATIZATION: "Climatização",
  ELECTRICAL: "Elétrica",
  IT: "T.I.",
};

export const defaultProFlowServices: ProFlowServiceCatalogItem[] = [
  {
    id: "svc-clima-install",
    name: "Instalação de ar-condicionado",
    area: "CLIMATIZATION",
    description: "Instalação completa, testes de funcionamento e orientação ao cliente.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 90,
    checklist: ["Conferir tensão e circuito", "Verificar tubulação e isolamento", "Testar drenagem", "Testar temperatura e corrente", "Registrar fotos finais"],
    active: true,
  },
  {
    id: "svc-clima-clean",
    name: "Higienização de ar-condicionado",
    area: "CLIMATIZATION",
    description: "Limpeza técnica de evaporadora, filtros, bandeja, dreno e inspeção funcional.",
    unit: "UNIT",
    priceCents: 0,
    warrantyDays: 30,
    checklist: ["Foto antes", "Limpar filtros", "Limpar evaporadora", "Verificar dreno", "Teste final e foto depois"],
    active: true,
  },
  {
    id: "svc-clima-corrective",
    name: "Manutenção corretiva",
    area: "CLIMATIZATION",
    description: "Diagnóstico, correção de falha e teste operacional.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 90,
    checklist: ["Registrar sintoma", "Diagnóstico", "Medições", "Correção executada", "Teste final"],
    active: true,
  },
  {
    id: "svc-eletrica-visit",
    name: "Visita técnica elétrica",
    area: "ELECTRICAL",
    description: "Inspeção, diagnóstico e orientação técnica de instalações elétricas.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 0,
    checklist: ["Identificar circuito", "Medições de tensão", "Verificar proteções", "Registrar diagnóstico", "Orientar cliente"],
    active: true,
  },
  {
    id: "svc-eletrica-install",
    name: "Instalação elétrica",
    area: "ELECTRICAL",
    description: "Execução de pontos, circuitos, tomadas, iluminação ou adequações elétricas.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 90,
    checklist: ["Desenergizar circuito", "Conferir bitola e proteção", "Executar instalação", "Testar continuidade e tensão", "Registrar entrega"],
    active: true,
  },
  {
    id: "svc-it-visit",
    name: "Visita técnica de T.I.",
    area: "IT",
    description: "Diagnóstico e suporte técnico presencial em computadores, rede, servidor, impressoras ou outros periféricos.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 7,
    checklist: ["Registrar solicitação do cliente", "Identificar equipamentos envolvidos", "Executar diagnóstico", "Registrar alterações realizadas", "Validar funcionamento com o usuário", "Orientar o cliente ou equipe"],
    active: true,
  },
  {
    id: "svc-it-computer-maintenance",
    name: "Manutenção de computador ou notebook",
    area: "IT",
    description: "Diagnóstico, manutenção preventiva ou corretiva, limpeza lógica, otimização e validação de computador ou notebook.",
    unit: "UNIT",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Registrar estado inicial", "Verificar hardware e armazenamento", "Verificar sistema e inicialização", "Executar manutenção ou correção", "Atualizar quando aplicável", "Testar desempenho e periféricos", "Registrar serviço concluído"],
    active: true,
  },
  {
    id: "svc-it-format-os",
    name: "Formatação e instalação do sistema operacional",
    area: "IT",
    description: "Backup combinado com o cliente, formatação, instalação do Windows, drivers, atualizações e configurações essenciais.",
    unit: "UNIT",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Confirmar arquivos que devem ser preservados", "Realizar backup quando contratado", "Formatar unidade", "Instalar sistema operacional", "Instalar drivers", "Aplicar atualizações", "Configurar usuário e itens essenciais", "Testar reinicialização, rede, áudio e vídeo"],
    active: true,
  },
  {
    id: "svc-it-software",
    name: "Instalação e configuração de software",
    area: "IT",
    description: "Instalação, atualização e configuração de aplicativos, drivers e componentes necessários ao ambiente do cliente.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 7,
    checklist: ["Validar requisitos e licença", "Criar ponto de restauração quando aplicável", "Instalar ou atualizar", "Configurar aplicação", "Testar funcionamento", "Orientar usuário"],
    active: true,
  },
  {
    id: "svc-it-network",
    name: "Configuração de rede local e compartilhamento",
    area: "IT",
    description: "Configuração de rede local, descoberta de dispositivos, compartilhamentos, permissões e acesso entre computadores.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Mapear computadores e dispositivos", "Verificar endereçamento e conectividade", "Configurar rede e descoberta", "Configurar compartilhamentos", "Definir permissões", "Testar acesso em cada estação", "Documentar computadores validados", "Orientar equipe"],
    active: true,
  },
  {
    id: "svc-it-shared-folder",
    name: "Configuração de pasta compartilhada e permissões",
    area: "IT",
    description: "Criação ou reorganização de pasta centralizada em servidor ou computador, definição de permissões e liberação do acesso nas estações de trabalho.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Definir local da pasta central", "Verificar espaço e permissões", "Criar ou configurar compartilhamento", "Definir usuários e permissões", "Mapear acesso nas estações", "Testar leitura e gravação em cada computador", "Registrar estações configuradas", "Orientar equipe sobre o uso"],
    active: true,
  },
  {
    id: "svc-it-server",
    name: "Configuração de servidor",
    area: "IT",
    description: "Configuração de serviços, pastas, usuários, permissões, rotinas de backup e acesso das estações ao servidor.",
    unit: "HOUR",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Registrar configuração atual", "Realizar backup antes da alteração quando aplicável", "Mapear ambiente e usuários", "Executar configuração", "Configurar permissões", "Testar acesso das estações", "Validar serviços após reinicialização quando aplicável", "Documentar alterações"],
    active: true,
  },
  {
    id: "svc-it-backup",
    name: "Configuração de backup",
    area: "IT",
    description: "Configuração ou revisão de rotina de backup local, em rede ou em unidade externa, com teste de gravação e recuperação.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Identificar dados críticos", "Definir destino do backup", "Verificar capacidade disponível", "Configurar rotina", "Executar primeiro backup", "Testar acesso ou restauração de amostra", "Registrar periodicidade e destino", "Orientar responsável"],
    active: true,
  },
  {
    id: "svc-it-printer",
    name: "Instalação e configuração de impressora ou scanner",
    area: "IT",
    description: "Instalação de driver, configuração local ou em rede, compartilhamento e teste de impressão ou digitalização.",
    unit: "UNIT",
    priceCents: 0,
    warrantyDays: 7,
    checklist: ["Identificar modelo e conexão", "Instalar driver", "Configurar rede ou compartilhamento", "Adicionar nas estações necessárias", "Testar impressão", "Testar digitalização quando aplicável", "Orientar usuário"],
    active: true,
  },
  {
    id: "svc-it-router-switch",
    name: "Configuração de roteador, switch ou ponto de rede",
    area: "IT",
    description: "Instalação, configuração e teste de roteadores, switches e pontos de rede para conectividade do ambiente.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Mapear topologia", "Registrar configuração existente", "Instalar ou configurar equipamento", "Validar endereçamento", "Testar conectividade", "Testar dispositivos principais", "Documentar alterações"],
    active: true,
  },
  {
    id: "svc-it-cabling",
    name: "Cabeamento e organização de rede",
    area: "IT",
    description: "Lançamento, organização, conectorização e teste de cabos e pontos de rede para estações e equipamentos.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 90,
    checklist: ["Definir percurso", "Conferir materiais", "Executar cabeamento", "Conectorizar pontos", "Identificar cabos e portas", "Testar conectividade", "Registrar pontos instalados"],
    active: true,
  },
  {
    id: "svc-it-workstations",
    name: "Configuração de estações de trabalho",
    area: "IT",
    description: "Preparação e padronização de computadores de uma empresa ou clínica, incluindo rede, usuários, softwares, compartilhamentos e periféricos.",
    unit: "UNIT",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Identificar estação e responsável", "Verificar sistema e rede", "Configurar usuário", "Instalar ou configurar softwares necessários", "Configurar compartilhamentos", "Configurar impressoras e periféricos quando aplicável", "Testar acessos", "Registrar estação concluída"],
    active: true,
  },
  {
    id: "svc-it-device-integration",
    name: "Integração de equipamento com rede ou computador",
    area: "IT",
    description: "Integração de equipamentos técnicos, clínicos ou comerciais com computadores, servidor, pasta compartilhada ou rede local para troca e armazenamento de arquivos.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 15,
    checklist: ["Identificar equipamento e finalidade", "Registrar configuração atual", "Verificar conectividade", "Configurar destino ou compartilhamento", "Configurar acesso nos computadores envolvidos", "Executar teste real de envio ou acesso", "Registrar estações validadas", "Orientar equipe"],
    active: true,
  },
  {
    id: "svc-it-remote-support",
    name: "Suporte técnico remoto",
    area: "IT",
    description: "Atendimento remoto para diagnóstico, configuração de software, ajustes de sistema, rede e orientação ao usuário.",
    unit: "HOUR",
    priceCents: 0,
    warrantyDays: 7,
    checklist: ["Registrar solicitação", "Confirmar autorização de acesso", "Diagnosticar", "Executar ajuste", "Validar com usuário", "Registrar o que foi alterado"],
    active: true,
  },
  {
    id: "svc-it-data-transfer",
    name: "Backup e transferência de arquivos",
    area: "IT",
    description: "Cópia, organização e transferência de arquivos entre computadores, discos ou outros destinos definidos pelo cliente.",
    unit: "SERVICE",
    priceCents: 0,
    warrantyDays: 7,
    checklist: ["Definir origem e destino", "Verificar espaço disponível", "Confirmar pastas incluídas", "Executar cópia", "Validar quantidade e amostras de arquivos", "Registrar destino final"],
    active: true,
  },
  {
    id: "svc-it-team-guidance",
    name: "Orientação técnica da equipe",
    area: "IT",
    description: "Orientação aos usuários após implantação ou ajuste, com demonstração do fluxo correto e cuidados básicos de utilização.",
    unit: "HOUR",
    priceCents: 0,
    warrantyDays: 0,
    checklist: ["Definir usuários participantes", "Demonstrar fluxo", "Explicar acessos e permissões", "Responder dúvidas", "Registrar orientação realizada"],
    active: true,
  },
];
