"use client";

import Link from "next/link";
import { Archive, ArrowRight, BarChart3, BriefcaseBusiness, LayoutGrid, List, MoreHorizontal, Pencil, Plus, Search, UserPlus, UsersRound } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { MetricItem, MetricStrip } from "@/components/ui/metric-strip";
import { PageHeader, PageHeaderActions, PageHeaderContent, PageHeaderHeading, PageHeaderIcon, PageHeaderIdentity, PageHeaderToolbar } from "@/components/ui/page-header";
import { Select } from "@/components/ui/select";
import { TableSkeleton } from "@/components/ui/skeleton";
import { Table } from "@/components/ui/table";
import { cn } from "@/lib/utils";
import { archiveCrmLeadAction, listCrmLeadsAction, moveCrmLeadAction, updateCrmLeadAction } from "./crm-actions";
import { crmStages } from "./crm-data";
import { CrmLeadForm } from "./crm-lead-form";
import type { CrmLeadFormValues } from "./crm-schema";
import type { CrmLeadRecord, CrmStageId } from "./crm-types";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const priorityLabels = { LOW: "Baixa", MEDIUM: "Média", HIGH: "Alta", CRITICAL: "Crítica" } as const;
function LeadCard({ lead, busy, onEdit, onArchive, onMove }: { lead: CrmLeadRecord; busy: boolean; onEdit: () => void; onArchive: () => void; onMove: (stage: CrmStageId) => void }) {
  return <Card className="group border-border shadow-none hover:border-sky-300 hover:shadow-sm"><CardContent className="space-y-2 p-2.5">
    <div className="flex items-start justify-between gap-2"><Badge variant="outline">{lead.serviceInterest}</Badge><Button type="button" variant="ghost" size="icon" className="h-7 w-7" onClick={onEdit} aria-label={`Editar ${lead.name}`}><MoreHorizontal className="h-4 w-4" /></Button></div>
    <Link href={`/dashboard/crm/${lead.id}`} className="block text-sm font-semibold hover:text-sky-600">{lead.name}</Link>
    <div className="grid grid-cols-2 gap-2 border-y py-2 text-xs"><div><span className="block text-muted-foreground">Valor</span><strong>{money.format(lead.estimatedValue)}</strong></div><div><span className="block text-muted-foreground">Responsável</span><strong className="line-clamp-1">{lead.salesOwner}</strong></div></div>
    <div className="flex items-center justify-between gap-2"><span className="text-[0.68rem] text-muted-foreground">Prioridade {priorityLabels[lead.priority].toLowerCase()}</span><Select value={lead.stageId} onChange={(event) => onMove(event.target.value as CrmStageId)} disabled={busy} className="h-7 w-28 text-[0.68rem]">{crmStages.map((stage) => <option key={stage.id} value={stage.id}>{stage.title}</option>)}</Select></div>
    <div className="flex justify-end gap-1"><Button asChild variant="ghost" size="sm"><Link href={`/dashboard/crm/${lead.id}`}>Detalhes<ArrowRight className="h-3.5 w-3.5" /></Link></Button><Button variant="ghost" size="icon" onClick={onArchive} disabled={busy} aria-label={`Arquivar ${lead.name}`}><Archive className="h-4 w-4" /></Button></div>
  </CardContent></Card>;
}

export function CrmBoard() {
  const [leads, setLeads] = useState<CrmLeadRecord[]>([]), [loading, setLoading] = useState(true), [busyId, setBusyId] = useState<string | null>(null);
  const [search, setSearch] = useState(""), [stageFilter, setStageFilter] = useState("ALL"), [view, setView] = useState<"kanban" | "list">("kanban");
  const [editing, setEditing] = useState<CrmLeadRecord | null>(null), [archiving, setArchiving] = useState<CrmLeadRecord | null>(null), [feedback, setFeedback] = useState<{ tone: "success" | "error"; message: string } | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setLeads(await listCrmLeadsAction()); } catch (error) { setFeedback({ tone: "error", message: error instanceof Error ? error.message : "Não foi possível carregar o CRM." }); } finally { setLoading(false); } }, []);
  useEffect(() => { let active = true; void listCrmLeadsAction().then((items) => { if (active) setLeads(items); }).catch((error: unknown) => { if (active) setFeedback({ tone: "error", message: error instanceof Error ? error.message : "Não foi possível carregar o CRM." }); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const filtered = useMemo(() => { const term = search.trim().toLocaleLowerCase("pt-BR"); return leads.filter((lead) => (stageFilter === "ALL" || lead.stageId === stageFilter) && (!term || [lead.name, lead.serviceInterest, lead.salesOwner, lead.source, lead.city].some((value) => value.toLocaleLowerCase("pt-BR").includes(term)))); }, [leads, search, stageFilter]);
  const byStage = (id: CrmStageId) => filtered.filter((lead) => lead.stageId === id);
  async function move(lead: CrmLeadRecord, stage: CrmStageId) { setBusyId(lead.id); try { await moveCrmLeadAction(lead.id, stage); await load(); setFeedback({ tone: "success", message: "Etapa atualizada." }); } catch (error) { setFeedback({ tone: "error", message: error instanceof Error ? error.message : "Não foi possível mover o lead." }); } finally { setBusyId(null); } }
  async function save(values: CrmLeadFormValues) { if (!editing) return; setBusyId(editing.id); try { await updateCrmLeadAction(editing.id, values); setEditing(null); await load(); setFeedback({ tone: "success", message: "Lead atualizado com sucesso." }); } catch (error) { setFeedback({ tone: "error", message: error instanceof Error ? error.message : "Não foi possível editar o lead." }); } finally { setBusyId(null); } }
  async function archive() { if (!archiving) return; setBusyId(archiving.id); try { await archiveCrmLeadAction(archiving.id); setArchiving(null); await load(); setFeedback({ tone: "success", message: "Lead arquivado." }); } catch (error) { setFeedback({ tone: "error", message: error instanceof Error ? error.message : "Não foi possível arquivar." }); } finally { setBusyId(null); } }
  const total = leads.reduce((sum, lead) => sum + lead.estimatedValue, 0), approved = leads.filter((lead) => lead.stageId === "approved"), converted = leads.filter((lead) => lead.convertedClientId).length;
  return <div className="space-y-3">
    <PageHeader><PageHeaderContent><PageHeaderIdentity><PageHeaderIcon><BarChart3 className="h-5 w-5" /></PageHeaderIcon><PageHeaderHeading title="CRM · Pipeline" description="Oportunidades comerciais persistidas por etapa." /></PageHeaderIdentity><PageHeaderActions><div className="flex rounded-lg border p-1"><Button variant="ghost" size="sm" onClick={() => setView("kanban")} aria-pressed={view === "kanban"}><LayoutGrid className="h-4 w-4" />Kanban</Button><Button variant="ghost" size="sm" onClick={() => setView("list")} aria-pressed={view === "list"}><List className="h-4 w-4" />Lista</Button></div><Button asChild size="sm"><Link href="/dashboard/crm/novo-lead"><Plus className="h-4 w-4" />Novo lead</Link></Button></PageHeaderActions></PageHeaderContent><PageHeaderToolbar className="grid gap-2 lg:grid-cols-[1fr_13rem]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Pesquisar lead, interesse, responsável ou origem..." className="pl-9" /></div><Select value={stageFilter} onChange={(event) => setStageFilter(event.target.value)}><option value="ALL">Todas as etapas</option>{crmStages.map((stage) => <option key={stage.id} value={stage.id}>{stage.title}</option>)}</Select></PageHeaderToolbar></PageHeader>
    <MetricStrip className="sm:min-w-0 sm:grid-flow-row sm:grid-cols-2 xl:grid-cols-4"><MetricItem label="Leads ativos" value={String(leads.length)} description="Oportunidades não arquivadas" icon={<UsersRound className="h-4 w-4" />} tone="info" /><MetricItem label="Valor no pipeline" value={money.format(total)} description="Soma das oportunidades" icon={<BriefcaseBusiness className="h-4 w-4" />} tone="violet" /><MetricItem label="Aprovados" value={money.format(approved.reduce((sum, lead) => sum + lead.estimatedValue, 0))} description={`${approved.length} oportunidades`} tone="success" /><MetricItem label="Convertidos" value={String(converted)} description="Clientes originados do CRM" icon={<UserPlus className="h-4 w-4" />} tone="warning" /></MetricStrip>
    {loading ? <TableSkeleton rows={6} columns={7} /> : view === "kanban" ? <section className="proflow-scrollbar overflow-x-auto rounded-xl border bg-muted/20 p-2"><div className="flex min-w-max items-start gap-2">{crmStages.map((stage) => { const items = byStage(stage.id); return <section key={stage.id} className="w-[16rem] shrink-0 rounded-xl border bg-muted/40 p-2"><header className="mb-2 flex items-start justify-between border-b pb-2"><div><div className="flex items-center gap-2"><h2 className="text-xs font-semibold">{stage.title}</h2><Badge variant="neutral">{items.length}</Badge></div><strong className="mt-1 block text-[0.68rem]">{money.format(items.reduce((sum, lead) => sum + lead.estimatedValue, 0))}</strong></div></header><div className="space-y-2">{items.map((lead) => <LeadCard key={lead.id} lead={lead} busy={busyId === lead.id} onEdit={() => setEditing(lead)} onArchive={() => setArchiving(lead)} onMove={(next) => void move(lead, next)} />)}{items.length === 0 ? <EmptyState size="compact" title="Nenhum lead nesta etapa" description="As oportunidades aparecerão aqui." /> : null}</div></section>; })}</div></section> : <Table density="compact" scrollHint stickyHeader striped className="min-w-[70rem]"><thead><tr><th>Lead</th><th>Etapa</th><th>Prioridade</th><th>Responsável</th><th>Origem</th><th data-align="right">Valor</th><th data-align="right">Ações</th></tr></thead><tbody>{filtered.map((lead) => <tr key={lead.id}><td><Link className="font-semibold hover:text-sky-600" href={`/dashboard/crm/${lead.id}`}>{lead.name}</Link><span className="block text-xs text-muted-foreground">{lead.serviceInterest}</span></td><td><Select value={lead.stageId} onChange={(event) => void move(lead, event.target.value as CrmStageId)} disabled={busyId === lead.id}>{crmStages.map((stage) => <option key={stage.id} value={stage.id}>{stage.title}</option>)}</Select></td><td>{priorityLabels[lead.priority]}</td><td>{lead.salesOwner}</td><td>{lead.source}</td><td data-align="right" className="font-semibold tabular-nums">{money.format(lead.estimatedValue)}</td><td data-align="right"><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => setEditing(lead)} aria-label={`Editar ${lead.name}`}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => setArchiving(lead)} aria-label={`Arquivar ${lead.name}`}><Archive className="h-4 w-4" /></Button></div></td></tr>)}{filtered.length === 0 ? <tr><td colSpan={7}><EmptyState size="compact" title="Nenhum lead encontrado" description={leads.length ? "Ajuste a busca ou os filtros." : "Cadastre o primeiro lead."} /></td></tr> : null}</tbody></Table>}
    {editing ? <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/55"><section role="dialog" aria-modal="true" aria-labelledby="edit-lead-title" className="h-full w-full max-w-3xl overflow-y-auto bg-background p-5 shadow-2xl"><div className="mb-4 flex justify-between"><div><h2 id="edit-lead-title" className="font-semibold">Editar lead</h2><p className="text-xs text-muted-foreground">Atualize dados e etapa da oportunidade.</p></div><Button variant="secondary" onClick={() => setEditing(null)} disabled={busyId === editing.id}>Fechar</Button></div><CrmLeadForm lead={editing} saving={busyId === editing.id} onSubmit={save} /></section></div> : null}
    {archiving ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><section role="alertdialog" aria-modal="true" aria-labelledby="archive-title" className="w-full max-w-md rounded-xl border bg-card p-5"><h2 id="archive-title" className="font-semibold">Arquivar lead?</h2><p className="mt-2 text-sm text-muted-foreground">{archiving.name} deixará de aparecer no pipeline, mas continuará salvo no histórico local.</p><div className="mt-4 flex justify-end gap-2"><Button autoFocus variant="secondary" onClick={() => setArchiving(null)} disabled={busyId === archiving.id}>Cancelar</Button><Button variant="destructive" onClick={() => void archive()} disabled={busyId === archiving.id}>{busyId === archiving.id ? "Arquivando..." : "Arquivar"}</Button></div></section></div> : null}
    {feedback ? <div role={feedback.tone === "error" ? "alert" : "status"} className={cn("fixed bottom-4 right-4 z-[60] max-w-sm rounded-xl border bg-card p-3 text-sm shadow-xl", feedback.tone === "error" ? "text-rose-600" : "text-emerald-600")}>{feedback.message}</div> : null}
  </div>;
}
