import type { ConfigState } from "./configuracoes-types";
const now = () => new Date().toISOString();
const numbering = (prefix: string, digits = 4) => ({
  prefix,
  nextNumber: 1,
  digits,
  includeYear: true,
  separator: "-",
});
export const defaultConfigState = (): ConfigState => ({
  version: 1,
  revision: 0,
  company: {
    legalName: "",
    tradeName: "",
    document: "",
    stateRegistration: "",
    municipalRegistration: "",
    phone: "",
    whatsapp: "",
    email: "",
    website: "",
    address: "",
    city: "",
    state: "BA",
    zipCode: "",
    legalRepresentative: "",
    notes: "",
    segment: "SERVICOS_TECNICOS",
    specialties: [],
    businessHours: "Segunda a sexta, 08:00 às 18:00",
    displayName: "ProFlow",
    shortName: "ProFlow",
    logoMetadata: "",
    iconMetadata: "",
    primaryColor: "#0284c7",
    secondaryColor: "#0f172a",
    documentHeader: "",
    documentFooter: "",
    textualSignature: "",
    updatedAt: now(),
  },
  teamMembers: [],
  operationalSettings: {
    serviceOrder: {
      prefix: "OS",
      sequenceDigits: 4,
      statuses: ["OPEN", "SCHEDULED", "IN_PROGRESS", "COMPLETED", "CANCELED"],
      priorities: ["LOW", "NORMAL", "HIGH", "URGENT"],
      categories: [
        "CLIMATIZATION",
        "ELECTRICAL",
        "PREVENTIVE",
        "CORRECTIVE",
        "INSTALLATION",
      ],
      defaultDurationMinutes: 120,
      initialStatus: "OPEN",
      terminalStatuses: ["COMPLETED", "CANCELED"],
    },
    agenda: {
      startTime: "08:00",
      endTime: "18:00",
      defaultDurationMinutes: 60,
      workingDays: [1, 2, 3, 4, 5],
      timezone: "America/Sao_Paulo",
      initialView: "week",
      blockConflicts: true,
    },
    stock: {
      categories: [
        "REFRIGERATION",
        "ELECTRICAL",
        "SAFETY",
        "CONSUMABLES",
        "CLEANING",
        "OTHER",
      ],
      units: ["UNIT", "PAIR", "METER", "KILOGRAM", "LITER", "BOX", "PACKAGE", "ROLL"],
      allowNegative: false,
      costMethod: "WEIGHTED_AVERAGE",
    },
    equipment: {
      categories: ["Ferramentas", "Medição", "Veículos", "Informática"],
      types: ["TOOL", "VEHICLE", "COMPUTER", "MEASUREMENT_INSTRUMENT", "OTHER"],
      statuses: [
        "AVAILABLE",
        "IN_USE",
        "UNDER_MAINTENANCE",
        "INACTIVE",
        "RETIRED",
        "LOST",
      ],
      conditions: ["GOOD", "ATTENTION", "DAMAGED", "UNUSABLE"],
      depreciationMethod: "LINEAR",
    },
  },
  financialSettings: {
    currency: "BRL",
    defaultAccountId: "",
    revenueCategories: ["Serviços", "Vendas"],
    expenseCategories: ["Materiais", "Operacional", "Manutenção"],
    investmentCategories: ["Equipamentos", "Infraestrutura"],
    paymentMethods: ["Pix", "Dinheiro", "Cartão", "Transferência", "Boleto"],
    defaultDueDays: 30,
    defaultInstallments: 1,
    allowOverpayment: false,
  },
  pricingSettings: {
    minimumMarginBasisPoints: 2000,
    recommendedMarginBasisPoints: 3500,
    premiumMarginBasisPoints: 5000,
    taxBasisPoints: 0,
    commissionBasisPoints: 0,
    laborBurdenBasisPoints: 0,
    equipmentMonthlyHours: 176,
    technicalLossBasisPoints: 0,
    costPerKmCents: 0,
    overheadBasisPoints: 0,
    requireBelowMinimumConfirmation: true,
    rounding: "NONE",
  },
  numberingSettings: {
    serviceOrders: numbering("OS"),
    financial: numbering("FIN"),
    clients: numbering("CLI"),
    leads: numbering("LEAD"),
    equipment: numbering("EQ"),
    stock: numbering("EST"),
    purchases: numbering("COMP"),
    pricing: numbering("PREC"),
    templates: numbering("TPL"),
  },
  appearanceSettings: {
    theme: "system",
    density: "comfortable",
    radius: "default",
    contrast: "normal",
    accent: "sky",
    fontSize: "normal",
    reducedMotion: false,
  },
  systemPreferences: {
    dateFormat: "DD/MM/YYYY",
    timeFormat: "24h",
    language: "pt-BR",
    timezone: "America/Sao_Paulo",
    tableRows: 25,
    moduleInitialViews: {},
    confirmDeletion: true,
    confirmArchiving: true,
    openDetails: "same-tab",
    preserveFilters: true,
    internalNotifications: true,
  },
  history: [],
});
