import { z } from "zod";
const history = z.object({
  id: z.string().uuid(),
  type: z.string(),
  description: z.string(),
  createdAt: z.iso.datetime(),
});
const stringArray = z.array(z.string().min(1));
export const companySchema = z.object({
  legalName: z.string().max(150),
  tradeName: z.string().max(150),
  document: z.string().max(18),
  stateRegistration: z.string().max(30),
  municipalRegistration: z.string().max(30),
  phone: z.string().max(20),
  whatsapp: z.string().max(20),
  email: z.union([z.literal(""), z.email()]),
  website: z.string().max(200),
  address: z.string().max(200),
  city: z.string().max(100),
  state: z.enum([
    "AC",
    "AL",
    "AP",
    "AM",
    "BA",
    "CE",
    "DF",
    "ES",
    "GO",
    "MA",
    "MT",
    "MS",
    "MG",
    "PA",
    "PB",
    "PR",
    "PE",
    "PI",
    "RJ",
    "RN",
    "RS",
    "RO",
    "RR",
    "SC",
    "SP",
    "SE",
    "TO",
  ]),
  zipCode: z.string().max(9),
  legalRepresentative: z.string().max(120),
  notes: z.string().max(1000),
  segment: z.string(),
  specialties: stringArray,
  businessHours: z.string().max(200),
  displayName: z.string().min(1).max(80),
  shortName: z.string().min(1).max(30),
  logoMetadata: z.string().max(300),
  iconMetadata: z.string().max(300),
  primaryColor: z.string().regex(/^#[0-9a-f]{6}$/i),
  secondaryColor: z.string().regex(/^#[0-9a-f]{6}$/i),
  documentHeader: z.string().max(500),
  documentFooter: z.string().max(500),
  textualSignature: z.string().max(300),
  updatedAt: z.iso.datetime(),
});
export const teamMemberSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(2).max(120),
  role: z.string().min(1),
  specialties: stringArray,
  phone: z.string().max(20),
  email: z.union([z.literal(""), z.email()]),
  document: z.string().max(18).optional(),
  hourlyCostCents: z.number().int().safe().nonnegative(),
  burdenRateBasisPoints: z.number().int().min(0).max(100000),
  active: z.boolean(),
  colorIdentifier: z.string().max(30).optional(),
  availability: z.string().max(200),
  notes: z.string().max(1000),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  archivedAt: z.iso.datetime().optional(),
  history: z.array(history),
});
const numberingItem = z.object({
  prefix: z.string().max(15),
  nextNumber: z.number().int().positive().safe(),
  digits: z.number().int().min(1).max(12),
  includeYear: z.boolean(),
  separator: z.string().max(3),
});
export const configStateSchema = z.object({
  version: z.literal(1),
  revision: z.number().int().nonnegative(),
  company: companySchema,
  teamMembers: z.array(teamMemberSchema),
  operationalSettings: z.object({
    serviceOrder: z.object({
      prefix: z.string(),
      sequenceDigits: z.number().int().min(1).max(12),
      statuses: stringArray,
      priorities: stringArray,
      categories: stringArray,
      defaultDurationMinutes: z.number().int().positive(),
      initialStatus: z.string(),
      terminalStatuses: stringArray,
    }),
    agenda: z.object({
      startTime: z.string(),
      endTime: z.string(),
      defaultDurationMinutes: z.number().int().positive(),
      workingDays: z.array(z.number().int().min(0).max(6)),
      timezone: z.string(),
      initialView: z.string(),
      blockConflicts: z.boolean(),
    }),
    stock: z.object({
      categories: stringArray,
      units: stringArray,
      allowNegative: z.boolean(),
      costMethod: z.literal("WEIGHTED_AVERAGE"),
    }),
    equipment: z.object({
      categories: stringArray,
      types: stringArray,
      statuses: stringArray,
      conditions: stringArray,
      depreciationMethod: z.enum(["LINEAR", "NONE"]),
    }),
  }),
  financialSettings: z.object({
    currency: z.literal("BRL"),
    defaultAccountId: z.string(),
    revenueCategories: stringArray,
    expenseCategories: stringArray,
    investmentCategories: stringArray,
    paymentMethods: stringArray,
    defaultDueDays: z.number().int().nonnegative(),
    defaultInstallments: z.number().int().positive(),
    allowOverpayment: z.literal(false),
  }),
  pricingSettings: z.object({
    minimumMarginBasisPoints: z.number().int().nonnegative(),
    recommendedMarginBasisPoints: z.number().int().nonnegative(),
    premiumMarginBasisPoints: z.number().int().nonnegative(),
    taxBasisPoints: z.number().int().nonnegative(),
    commissionBasisPoints: z.number().int().nonnegative(),
    laborBurdenBasisPoints: z.number().int().nonnegative(),
    equipmentMonthlyHours: z.number().int().positive(),
    technicalLossBasisPoints: z.number().int().nonnegative(),
    costPerKmCents: z.number().int().nonnegative(),
    overheadBasisPoints: z.number().int().nonnegative(),
    requireBelowMinimumConfirmation: z.boolean(),
    rounding: z.string(),
  }),
  numberingSettings: z.record(z.string(), numberingItem),
  appearanceSettings: z.object({
    theme: z.enum(["light", "dark", "system"]),
    density: z.enum(["comfortable", "compact"]),
    radius: z.enum(["default", "rounded"]),
    contrast: z.enum(["normal", "high"]),
    accent: z.string(),
    fontSize: z.enum(["normal", "large"]),
    reducedMotion: z.boolean(),
  }),
  systemPreferences: z.object({
    dateFormat: z.literal("DD/MM/YYYY"),
    timeFormat: z.enum(["24h", "12h"]),
    language: z.literal("pt-BR"),
    timezone: z.string(),
    tableRows: z.number().int().min(5).max(200),
    moduleInitialViews: z.record(z.string(), z.string()),
    confirmDeletion: z.boolean(),
    confirmArchiving: z.boolean(),
    openDetails: z.enum(["same-tab", "new-tab"]),
    preserveFilters: z.boolean(),
    internalNotifications: z.boolean(),
  }),
  history: z.array(history),
});
