import { getClientAction } from "@/app/dashboard/clientes/actions"; import { agendaEventSchema, type AgendaEventFormValues } from "./agenda-schema"; import { AgendaRepository } from "./agenda-repository"; import type { AgendaDisplayEvent, AgendaHistory, AgendaIndependentEvent } from "./agenda-types";
const history = (type: AgendaHistory["type"], description: string): AgendaHistory => ({ id: crypto.randomUUID(), type, description, createdAt: new Date().toISOString() });
export class AgendaConflictError extends Error { constructor(public readonly conflicts: AgendaDisplayEvent[]) { super("O responsável já possui evento incompatível neste horário."); } }
const overlaps = (startA: string, endA: string, startB: string, endB: string) => startA < endB && endA > startB;
export class AgendaService { constructor(private readonly repository: AgendaRepository) {} listIndependent() { return this.repository.listIndependent(); } getIndependent(id: string) { return this.repository.findIndependent(id); } syncOrder(orderId: string) { return this.repository.upsertLink(orderId); }
  assertAvailability(value: AgendaEventFormValues, existing: AgendaDisplayEvent[], ignoredId?: string) { const conflicts = this.conflicts(value, existing.filter((event) => event.id !== ignoredId)); if (conflicts.length) throw new AgendaConflictError(conflicts); }
  async create(input: AgendaEventFormValues, existing: AgendaDisplayEvent[]) { const value = agendaEventSchema.parse(input); const client = value.clientId ? await getClientAction(value.clientId) : null; const seriesId = value.recurrence === "NONE" ? undefined : crypto.randomUUID(), now = new Date().toISOString(), records: AgendaIndependentEvent[] = []; for (let index = 0; index < value.occurrences; index++) { const date = new Date(`${value.date}T12:00:00`); if (value.recurrence === "WEEKLY") date.setDate(date.getDate() + index * 7); if (value.recurrence === "MONTHLY") date.setMonth(date.getMonth() + index); const dateValue = date.toISOString().slice(0, 10); this.assertAvailability({ ...value, date: dateValue }, existing); records.push({ id: crypto.randomUUID(), origin: "INDEPENDENT", title: value.title, type: value.type, description: value.description, responsible: value.responsible, clientId: client?.id, clientName: client?.name, date: dateValue, startTime: value.startTime, endTime: value.endTime, address: value.address, city: value.city, state: value.state.toUpperCase(), priority: value.priority, status: value.status, notes: value.notes, recurrence: value.recurrence, seriesId, occurrence: index + 1, createdAt: now, updatedAt: now, history: [history("CREATED", seriesId ? `Ocorrência ${index + 1} criada.` : "Evento criado.")] }); } for (const record of records) await this.repository.saveIndependent(record); return records[0]; }
  async update(id: string, input: AgendaEventFormValues, existing: AgendaDisplayEvent[]) { const current = await this.require(id), value = agendaEventSchema.parse(input); this.assertAvailability(value, existing, id); const events = [...current.history, history("UPDATED", "Evento atualizado.")]; if (current.date !== value.date || current.startTime !== value.startTime || current.endTime !== value.endTime) events.push(history("SCHEDULE", "Horário atualizado.")); if (current.responsible !== value.responsible) events.push(history("RESPONSIBLE", "Responsável atualizado.")); if (current.status !== value.status) events.push(history("STATUS", "Status atualizado.")); return this.repository.saveIndependent({ ...current, ...value, clientId: value.clientId || undefined, date: value.date, recurrence: current.recurrence, occurrence: current.occurrence, updatedAt: new Date().toISOString(), history: events }); }
  async cancel(id: string) { const current = await this.require(id), now = new Date().toISOString(); return this.repository.saveIndependent({ ...current, status: "CANCELED", canceledAt: now, updatedAt: now, history: [...current.history, history("CANCELED", "Evento cancelado.")] }); } async archive(id: string) { const current = await this.require(id), now = new Date().toISOString(); return this.repository.saveIndependent({ ...current, archivedAt: now, updatedAt: now, history: [...current.history, history("ARCHIVED", "Evento arquivado.")] }); }
  private conflicts(value: AgendaEventFormValues, events: AgendaDisplayEvent[]) { const start = `${value.date}T${value.startTime}:00`, end = `${value.date}T${value.endTime}:00`; return events.filter((event) => event.status !== "CANCELED" && event.technician.toLocaleLowerCase("pt-BR") === value.responsible.toLocaleLowerCase("pt-BR") && overlaps(start, end, event.startAt, event.endAt)); } private async require(id: string) { const event = await this.repository.findIndependent(id); if (!event) throw new Error("Evento não encontrado."); return event; } }
