import type { SupplierStorageState } from "./fornecedores-types";

export const initialSupplierState: SupplierStorageState = {
  version: 1,
  revision: 0,
  nextSequence: 3,
  suppliers: [
    {
      id: "supplier-1",
      sequence: 1,
      code: "FOR-0001",
      legalName: "Distribuidora Técnica Exemplo LTDA",
      tradeName: "Distribuidora Técnica Exemplo",
      document: "11222333000181",
      contactName: "Marcos Almeida",
      phone: "7332884455",
      whatsapp: "73988887777",
      email: "comercial@distribuidoraexemplo.com",
      city: "Porto Seguro",
      state: "BA",
      categories: ["CLIMATIZATION", "REFRIGERATION"],
      paymentTerms: "28 dias",
      preferredPaymentMethod: "Boleto",
      deliveryLeadTimeDays: 3,
      minimumOrderCents: 50000,
      rating: 4.5,
      status: "ACTIVE",
      notes: "Fornecedor demonstrativo para carga inicial.",
      createdAt: "2026-01-10T09:00:00.000Z",
      updatedAt: "2026-07-10T14:30:00.000Z",
      history: [{ id: "supplier-history-1", type: "CREATED", description: "Fornecedor criado na carga inicial.", createdAt: "2026-01-10T09:00:00.000Z" }],
    },
    {
      id: "supplier-2",
      sequence: 2,
      code: "FOR-0002",
      legalName: "Materiais Elétricos Exemplo LTDA",
      tradeName: "Materiais Elétricos Exemplo",
      document: "45987654000155",
      contactName: "Ana Costa",
      phone: "1134567890",
      email: "vendas@materiaisexemplo.com",
      city: "Eunápolis",
      state: "BA",
      categories: ["ELECTRICAL", "SAFETY"],
      paymentTerms: "À vista ou 14 dias",
      preferredPaymentMethod: "Pix",
      deliveryLeadTimeDays: 2,
      rating: 4,
      status: "ACTIVE",
      createdAt: "2026-02-05T10:00:00.000Z",
      updatedAt: "2026-06-28T11:15:00.000Z",
      history: [{ id: "supplier-history-2", type: "CREATED", description: "Fornecedor criado na carga inicial.", createdAt: "2026-02-05T10:00:00.000Z" }],
    },
  ],
};
