"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, CalendarClock, Edit3, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { PageHeader, PageHeaderActions, PageHeaderContent, PageHeaderHeading, PageHeaderIcon, PageHeaderIdentity } from "@/components/ui/page-header";
import { SectionHeader } from "@/components/ui/section-header";
import { archiveAgendaEventAction, cancelAgendaEventAction, getAgendaEventAction, updateAgendaEventAction } from "../agenda-actions";
import { AgendaEventFormDrawer } from "../agenda-event-form-drawer";
import { AgendaConflictError } from "../agenda-service";
import type { AgendaEventFormValues } from "../agenda-schema";
import type { AgendaDisplayEvent } from "../agenda-types";
const dateTime = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" });
export function AgendaDetail({ id }: { id: string }) {
  const [event, setEvent] = useState<AgendaDisplayEvent | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [drawer, setDrawer] = useState(false); const [busy, setBusy] = useState(false); const [formError, setFormError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { setEvent(await getAgendaEventAction(id)); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar."); } finally { setLoading(false); } }, [id]); useEffect(() => { void getAgendaEventAction(id).then(setEvent).catch((e: unknown) => setError(e instanceof Error ? e.message : "Não foi possível carregar.")).finally(() => setLoading(false)); }, [id]);
  const update = async (value: AgendaEventFormValues) => { setBusy(true); setFormError(""); try { await updateAgendaEventAction(id, value); await load(); setDrawer(false); } catch (e) { setFormError(e instanceof AgendaConflictError ? `${e.message} ${e.conflicts.map((item) => item.title).join(", ")}.` : e instanceof Error ? e.message : "Não foi possível atualizar."); } finally { setBusy(false); } };
  const mutate = async (kind: "cancel" | "archive") => { if (!confirm(kind === "cancel" ? "Confirma o cancelamento deste evento?" : "Confirma o arquivamento lógico deste evento?")) return; setBusy(true); try { if (kind === "cancel") await cancelAgendaEventAction(id); else await archiveAgendaEventAction(id); if (kind === "archive") location.href = "/dashboard/agenda"; else await load(); } catch (e) { setError(e instanceof Error ? e.message : "A ação não foi concluída."); } finally { setBusy(false); } };
  if (loading) return <div className="rounded-xl border border-border bg-card p-8 text-center text-sm text-muted-foreground">Carregando evento...</div>; if (!event) return <EmptyState title="Evento não encontrado" description={error || "O evento pode ter sido arquivado ou removido da origem."} action={<Button asChild><Link href="/dashboard/agenda">Voltar à Agenda</Link></Button>} />;
  const duration = Math.round((new Date(event.endAt).getTime() - new Date(event.startAt).getTime()) / 60000);
  return <div className="space-y-3"><PageHeader><PageHeaderContent><PageHeaderIdentity><PageHeaderIcon><CalendarClock className="h-5 w-5" /></PageHeaderIcon><PageHeaderHeading title={event.title} description={event.origin === "SERVICE_ORDER" ? "Evento sincronizado; a Ordem de Serviço é a fonte dos dados operacionais." : "Evento independente da Agenda."} /></PageHeaderIdentity><PageHeaderActions><Button asChild variant="secondary"><Link href="/dashboard/agenda"><ArrowLeft className="h-4 w-4" />Agenda</Link></Button><Button onClick={() => setDrawer(true)}><Edit3 className="h-4 w-4" />Editar</Button></PageHeaderActions></PageHeaderContent></PageHeader>
    {error && <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_20rem]"><Card><CardHeader><SectionHeader compact title="Detalhes do compromisso" /></CardHeader><CardContent className="grid gap-4 text-sm sm:grid-cols-2"><Info label="Origem" value={event.origin === "SERVICE_ORDER" ? "Ordem de Serviço" : "Agenda"} /><Info label="Cliente" value={event.customer} /><Info label="Responsável" value={event.technician} /><Info label="Data e horário" value={`${dateTime.format(new Date(event.startAt))} até ${dateTime.format(new Date(event.endAt))}`} /><Info label="Duração" value={`${duration} minutos`} /><Info label="Localização" value={`${event.address}, ${event.city} - ${event.state}`} /><Info label="Prioridade" value={event.priority} /><Info label="Status" value={event.status} /><Info label="Descrição" value={event.description || "Não informada"} /><Info label="Observações" value={event.notes || "Não informadas"} /><Info label="Criado em" value={event.createdAt ? dateTime.format(new Date(event.createdAt)) : "Registrado na origem"} /><Info label="Atualizado em" value={event.updatedAt ? dateTime.format(new Date(event.updatedAt)) : "Sincronizado dinamicamente"} /></CardContent></Card>
      <div className="space-y-3">{event.origin === "SERVICE_ORDER" && <Card><CardHeader><SectionHeader compact title="Vínculos" /></CardHeader><CardContent className="space-y-2"><Badge variant="info">Fonte: Ordem de Serviço</Badge>{event.orderId && <Button asChild variant="secondary" className="w-full"><Link href={`/dashboard/ordens/${event.orderId}`}>Abrir {event.serviceOrderNumber}<ExternalLink className="h-4 w-4" /></Link></Button>}{event.clientId && <Button asChild variant="secondary" className="w-full"><Link href={`/dashboard/clientes/${event.clientId}`}>Abrir cliente<ExternalLink className="h-4 w-4" /></Link></Button>}<p className="text-xs text-muted-foreground">Cancelamento e arquivamento devem ser realizados na Ordem.</p></CardContent></Card>}{event.origin === "INDEPENDENT" && <Card><CardHeader><SectionHeader compact title="Ações" /></CardHeader><CardContent className="grid gap-2"><Button variant="secondary" disabled={busy || event.status === "CANCELED"} onClick={() => void mutate("cancel")}>Cancelar evento</Button><Button variant="destructive" disabled={busy} onClick={() => void mutate("archive")}>Arquivar evento</Button></CardContent></Card>}</div></div>
    <Card><CardHeader><SectionHeader compact title="Histórico" /></CardHeader><CardContent className="divide-y divide-border">{event.history.length ? [...event.history].reverse().map((item) => <div key={item.id} className="flex items-start justify-between gap-4 py-3 text-sm"><div><p className="font-medium">{item.description}</p><p className="text-xs text-muted-foreground">{item.type}</p></div><time className="whitespace-nowrap text-xs text-muted-foreground">{dateTime.format(new Date(item.createdAt))}</time></div>) : <p className="py-4 text-sm text-muted-foreground">Histórico mantido pela origem.</p>}</CardContent></Card>
    <AgendaEventFormDrawer open={drawer} event={event} busy={busy} error={formError} onClose={() => setDrawer(false)} onSubmit={update} /></div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-foreground">{value}</p></div>; }
