import type { StockCategory, StockSeedItem, StockUnit } from "./estoque-types";

export const stockCategoryLabels: Record<StockCategory, string> = {
  REFRIGERATION: "Refrigeração",
  ELECTRICAL: "Elétrica",
  SAFETY: "Segurança",
  CONSUMABLES: "Consumíveis",
  CLEANING: "Limpeza",
  OTHER: "Outros",
};

export const stockUnitLabels: Record<StockUnit, string> = {
  UNIT: "UN",
  PAIR: "Par",
  METER: "m",
  KILOGRAM: "kg",
  LITER: "L",
  BOX: "Caixa",
  PACKAGE: "Pacote",
  ROLL: "Rolo",
};

export const stockUnitScales: Record<StockUnit, number> = {
  UNIT: 1,
  PAIR: 1,
  METER: 1000,
  KILOGRAM: 1000,
  LITER: 1000,
  BOX: 1,
  PACKAGE: 1,
  ROLL: 1,
};

export const stockSeeds: StockSeedItem[] = [
  [
    "stock-1",
    "REF-COB-001",
    "Tubulação de cobre 1/4",
    "REFRIGERATION",
    "METER",
    8,
    20,
    1950,
    "Prateleira A1",
  ],
  [
    "stock-2",
    "REF-COB-002",
    "Tubulação de cobre 3/8",
    "REFRIGERATION",
    "METER",
    42,
    20,
    2875,
    "Prateleira A1",
  ],
  [
    "stock-3",
    "ELE-CAB-001",
    "Cabo flexível 2,5 mm²",
    "ELECTRICAL",
    "METER",
    180,
    80,
    465,
    "Prateleira B2",
  ],
  [
    "stock-4",
    "ELE-DIS-032",
    "Disjuntor bipolar 32 A",
    "ELECTRICAL",
    "UNIT",
    3,
    6,
    5800,
    "Gaveta B4",
  ],
  [
    "stock-5",
    "ELE-FIT-001",
    "Fita isolante profissional",
    "CONSUMABLES",
    "ROLL",
    24,
    10,
    1280,
    "Gaveta C1",
  ],
  [
    "stock-6",
    "REF-GAS-410",
    "Fluido refrigerante R-410A",
    "REFRIGERATION",
    "KILOGRAM",
    0,
    5,
    7800,
    "Área controlada D1",
  ],
  [
    "stock-7",
    "REF-SUP-001",
    "Suporte para condensadora",
    "REFRIGERATION",
    "UNIT",
    14,
    8,
    8900,
    "Prateleira E2",
  ],
  [
    "stock-8",
    "SEG-LUV-001",
    "Luva de proteção elétrica",
    "SAFETY",
    "PAIR",
    6,
    4,
    14500,
    "Armário de segurança",
  ],
  [
    "stock-9",
    "LIM-EVA-001",
    "Produto para limpeza de evaporadora",
    "CLEANING",
    "LITER",
    18,
    8,
    3250,
    "Prateleira F1",
  ],
  [
    "stock-10",
    "ELE-CON-032",
    "Contator tripolar 32 A",
    "ELECTRICAL",
    "UNIT",
    2,
    4,
    18400,
    "Gaveta B5",
  ],
];
