"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import type { ClientPublicReference } from "@/lib/contracts/clientes.contract";
import type { CrmPricingReference } from "@/lib/contracts/crm.contract";
import type { ServiceOrderPricingReference } from "@/lib/contracts/ordens.contract";
export function PricingRelationsDialog({ open, clients, leads, orders, initial, busy, onClose, onSave }: { open: boolean; clients: ClientPublicReference[]; leads: CrmPricingReference[]; orders: ServiceOrderPricingReference[]; initial: { clientId?: string; crmLeadId?: string; serviceOrderId?: string }; busy: boolean; onClose: () => void; onSave: (value: { clientId?: string; crmLeadId?: string; serviceOrderId?: string }) => void }) {
  const [value, setValue] = useState(initial); if (!open) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="relations-title" onKeyDown={(event) => { if (event.key === "Escape") onClose(); }}><div className="w-full max-w-xl space-y-4 rounded-xl border bg-background p-5 shadow-xl"><div><h2 id="relations-title" className="font-semibold">Vínculos comerciais</h2><p className="text-sm text-muted-foreground">Vincular não aplica preço à Ordem.</p></div><label className="grid gap-1 text-sm">Cliente<Select autoFocus value={value.clientId ?? ""} onChange={(e) => setValue({ ...value, clientId: e.target.value || undefined, serviceOrderId: undefined })}><option value="">Sem cliente</option>{clients.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></label><label className="grid gap-1 text-sm">Lead do CRM<Select value={value.crmLeadId ?? ""} onChange={(e) => setValue({ ...value, crmLeadId: e.target.value || undefined })}><option value="">Sem lead</option>{leads.map((item) => <option key={item.id} value={item.id}>{item.title} · {item.customerName}</option>)}</Select></label><label className="grid gap-1 text-sm">Ordem de Serviço<Select value={value.serviceOrderId ?? ""} onChange={(e) => setValue({ ...value, serviceOrderId: e.target.value || undefined })}><option value="">Sem Ordem</option>{orders.filter((item) => !value.clientId || item.clientId === value.clientId).map((item) => <option key={item.id} value={item.id}>{item.number} · {item.title}</option>)}</Select></label><div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClose}>Cancelar</Button><Button disabled={busy} onClick={() => onSave(value)}>{busy ? "Salvando..." : "Salvar vínculos"}</Button></div></div></div>;
}
